server:
  port: 8080
spring:
  application:
    name: note-service
  profiles:
    active: default
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
datasource:
  username: postgres
  password: Abcdefghijklm1
  postgres:
    url: jdbc:postgresql://localhost:5432/postgres
  sally:
    url: jdbc:postgresql://localhost:5432/sally
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
